services:
  - docker
osx_image: xcode10.1
jobs:
  include:
    - stage: Run tests
      script: ./Scripts/travis/test-Linux.sh
      os: linux
      dist: xenial
    - os: osx
      script: ./Scripts/travis/test-macOS.sh
    - stage: release new version
      script: ./Scripts/travis/new-release.sh
      os: osx
      if: branch = master AND type = push AND fork = false
    - stage: deploy to cocoapods
      script: ./Scripts/travis/deploy-to-cocoapods.sh
      os: osx
      if: branch = master and type = push AND fork = false
    - stage: publish documentation
      script: ./Scripts/travis/publish-documentation.sh
      os: osx
      if: branch = master AND type = push AND fork = false

